### ISSUE TITLE
[FEATURE] support 

### ISSUE THREAD

**Issue by willzhang** [redhat-actions/buildah-build#106]
### Is your feature request related to a problem? Please describe.

no

i don't want to build image ,i just want to do this with actions ? any suggestion?
```
REPO=example.com/example/shazam
buildah manifest create $REPO:latest
for IMGTAG in amd64 s390x ppc64le arm64; do \
        buildah manifest add $REPO:latest docker://$REPO:IMGTAG; \
    done
buildah manifest push --all $REPO:latest
```

### Describe the solution you'd like

```
    steps:
      - name: Buildah Action
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          source_image:  app01-v1.1.0-amd64, app01-v1.1.0--arm64
          tartet_image:  app01-v1.1.0
          push: docker.io/xxx/app01-v1.1.0
```
