### ISSUE TITLE
[FEATURE] Support `--jobs N` flag on buildah bud

### ISSUE THREAD

**Issue by anthr76** [redhat-actions/buildah-build#115]
### Is your feature request related to a problem? Please describe.

In order to possibly speed up builds support the `--jobs` argument

### Describe the solution you'd like

--jobs N

Run up to N concurrent stages in parallel. If the number of jobs is greater than 1, stdin will be read from /dev/null. If 0 is specified, then there is no limit on the number of jobs that run in parallel.

REF: https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md

### Additional context

This can help to greatly reduce build times for large multi-arch builds.

**Comment by akostadinov** [comment]
+1, for some reason adding as extra args seems to be ignored
```yaml
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/s390x,linux/ppc64le
          labels: ${{ steps.meta.outputs.labels }}
          layers: false
          oci: true
          tls-verify: true
          extra-args: |
            --squash
            --jobs=3
          build-args: |
            PORTA_IMAGE=quay.io/3scale/porta:free-sphinx
          containerfiles: |
            Containerfile
```

**Comment by snecklifter** [comment]
This is already possible using the `extra-args` input, which passes additional flags directly to `buildah bud`:

```yaml
- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    containerfiles: ./Containerfile
    extra-args: |
      --jobs 4
```

The `extra-args` input is the intended mechanism for passing buildah flags that don't have a dedicated action input. Adding a dedicated input for every buildah flag would create a maintenance burden as buildah evolves, so we use `extra-args` as the escape hatch for less common options.

Note that `--jobs` requires buildah 1.24+ (the ubuntu-24.04 runner ships 1.33.7, so this works on GitHub-hosted runners).
