### ISSUE TITLE
[FEATURE] buildah in container

### ISSUE THREAD

**Issue by amezin** [redhat-actions/buildah-build#124]
### Is your feature request related to a problem? Please describe.

Buildah version on Ubuntu 22.04 GitHub-hosted action runners is rather old (1.23.1 - from Ubuntu repositories), not supporting `--cache-to`. Even through mixing and matching packages from multiple Ubuntu releases, you can only get 1.28.2 - where registry cache still isn't working correctly.

### Describe the solution you'd like

Would be nice if this action supported running buildah in a container (i.e. `quay.io/buildah/stable` image) transparently. With the ability to get the built image in "host" podman storage.

### Describe alternatives you've considered

1. Just run the image using `podman`/`docker`. But then I completely lose the convenience of this action.

2. Run the entire workflow/job using buildah image. But I need the `ubuntu-22.04` environment for other steps. Passing the image between jobs as a tar archive artifact would be slow and could probably hit GitHub limits.

**Comment by snecklifter** [comment]
Valid feature request. Running buildah inside a container would allow users to get newer buildah versions regardless of the runner's OS. This could be implemented as an optional mode where the action pulls a buildah container image (e.g., `quay.io/buildah/stable`) and executes builds inside it.

As a workaround, you can use a container job today:

```yaml
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/buildah/stable
      options: --privileged
    steps:
      - uses: actions/checkout@v7
      - run: buildah bud -t my-image -f Containerfile .
```

Note this bypasses the action but gives you full control over the buildah version.

Keeping this open as a future enhancement.
