### ISSUE TITLE
[BUG] `entrypoint` configured as `]` when building from scratch with `ENTRYPOINT`-less base image

### ISSUE THREAD

**Issue by dannywebster** [redhat-actions/buildah-build#141]
### Version
redhat-actions/push-to-registry@v2

### Describe the bug

When building without a Containerfile, and using UBI8 (`ubi8/ubi-minimal:8.10` or any other for that matter) - and not specifying `entrypoint`,  `buildah config` ends up writing this:

```
/usr/bin/buildah config --entrypoint ] working-container
```

.. and the resulting image's manifest:

```
  "Entrypoint": [
         "/bin/sh",
         "-c",
         "]"
   ],
```

This bracket is being returned from [this line](https://github.com/redhat-actions/buildah-build/blob/7a95fa7ee0f02d552a32753e7414641a04307056/src/buildah.ts#L244).

Note, that the UBI image in question has no `ENTRYPOINT`, but does have a `CMD` as per its [Dockerfile](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=arm64&tag=8.3-298.1618432845&push_date=1618946153000&container-tabs=dockerfile&image=6643ab8b8cff801a49e30c7f). I saw in an older [buildah issue](https://github.com/containers/buildah/issues/564), that in the presence of an `ENTRYPOINT`, `CMD` should be ignored, but this doesn't seem to be the case, as when I _do_ specify an `entrypoint` to the action, we end up with both:

```
 "Cmd": [
                "/bin/bash"
            ],
            "Entrypoint": [
                "bash"
            ],
```

I've tried this with/without OCI - no difference.

### Steps to reproduce, workflow links, screenshots

This is all with `buildah version 1.33.7 (image-spec 1.1.0-rc.5, runtime-spec 1.1.0)`

The step and its enumerated inputs:

```
- name: Build Image via Buildah
      uses: redhat-actions/buildah-build@v2
      with:
        oci: true
        base-image: registry.access.redhat.com/ubi8/ubi-minimal:8.10
        image: localhost/foo
        tags: 0.1
        content: somedir
```

Cheers!
