### ISSUE TITLE
[FEATURE] Docker build secrets mount support

### ISSUE THREAD

**Issue by ainGitHub** [redhat-actions/buildah-build#143]
Docker suggest use mount secrets to build (https://docs.docker.com/build/building/secrets/ and https://docs.docker.com/reference/build-checks/secrets-used-in-arg-or-env/), not send sensitive data in build-args
For this reason, can your add that future for buildah-build action?

**Comment by mikepurvis** [comment]
Having general support for `buildah build --volume` in this action would be great—it's important when doing a build inside the container to be able to, say, extract a logs directory from a failed step.

**Comment by snecklifter** [comment]
This is already supported via the `extra-args` input:

```yaml
- name: Create secret file
  run: echo "${{ secrets.MY_SECRET }}" > ${{ runner.temp }}/my-secret

- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    containerfiles: ./Containerfile
    extra-args: |
      --secret id=my-secret,src=${{ runner.temp }}/my-secret
```

In your Containerfile:
```dockerfile
RUN --mount=type=secret,id=my-secret cat /run/secrets/my-secret
```

**Note:** `--mount=type=secret` requires buildah 1.24+. The ubuntu-24.04 runner ships buildah 1.33.7 which supports this. The secret is never written into any image layer, making this more secure than `build-args`.

Since this works well via `extra-args` and adding a dedicated `secrets` input would essentially duplicate the same `--secret` flag, closing this as already supported.
