### ISSUE TITLE
[BUG] Error: buildah exited with code 232

### ISSUE THREAD

**Issue by gchicoye** [redhat-actions/buildah-build#145]
### Version

```
Version:         1.33.7
Go Version:      go1.22.2
Image Spec:      1.1.0-rc.5
Runtime Spec:    1.1.0
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.29.2
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

### Describe the bug

Running on Github Actions the following action (we've added --ulimit on purpose after looking at documentation)
```
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: gchicoye/n360-exchange-ts
        tags: latest ${{ env.TAG }}
        # tags: ${{ env.TAG }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          --ulimit nofile=65535:65535
```

We get the following error on `RUN npm install` step

```
npm notice 
npm ERR! code EMFILE
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/index-v5/6c/6f/8e7e8934679b7b49b8240b1f2dcb66c25a5bd17f9629f8fe0ea634cab93c
npm ERR! errno -24
npm ERR! EMFILE: too many open files, open '/root/.npm/_cacache/index-v5/6c/6f/8e7e8934679b7b49b8240b1f2dcb66c25a5bd17f9629f8fe0ea634cab93c'
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2025-01-09T12_04_44_685Z-debug-0.log
Error: building at STEP "RUN npm install": while running runtime: exit status 232
Error: Error: buildah exited with code 232
```

### Steps to reproduce, workflow links, screenshots

A lot of files are opened by NPM install...

Thanks!
