### ISSUE TITLE
[FEATURE] `tags` field should be a YAML list not a space separated list

### ISSUE THREAD

**Issue by Nicolas-Peiffer** [redhat-actions/buildah-build#146]
### Is your feature request related to a problem? Please describe.

In the Github Action YAML configuration file, the `tags` field should be a YAML list, not a space separated list.
Indeed, YAML natively supports lists, so there is no reason to use a space separated list, other than not changing the source code which parses this YAML configuration.

Related issues:
 * https://github.com/redhat-actions/buildah-build/issues/146
 * https://github.com/redhat-actions/push-to-registry/issues/101

### Describe the solution you'd like

Use the list native support of YAML:

```yaml
      - name: Build the container image
        id: buildah-build
        uses: redhat-actions/buildah-build@v1
        with:
          image-name: ${{ steps.set-oci-image-url.outputs.oci_image_url }}
          containerfile: ${{ env.BASE_CONTAINERFILE_NAME }}
          tags:
            - ${{ github.sha }}
            - tag1
            - tag2
            - tag3
          oci: true
```

instead of a space separated list:

```yaml
      - name: Build the container image
        id: buildah-build
        uses: redhat-actions/buildah-build@v1
        with:
          image-name: ${{ steps.set-oci-image-url.outputs.oci_image_url }}
          containerfile: ${{ env.BASE_CONTAINERFILE_NAME }}
          tags: ${{ github.sha }} tag1 tag2 tag3
          oci: true
```

### Describe alternatives you've considered

I have a situation where I need to tag an OCI image with a list of multiple tags which are actualy Github Action variable from other steps of my job.

Below is an example of what 13 tags in a Github Action recipe could looks like:

```yaml
tags:
  - ${{ github.sha }}
  - golang-${{ steps.extract.outputs.golang_version }}
  - goreleaser-${{ steps.extract.outputs.goreleaser_version }}
  - cosign-${{ steps.extract.outputs.cosign_version }}
  - ko-${{ steps.extract.outputs.ko_version }}
  - trivy-${{ steps.extract.outputs.trivy_version }}
  - syft-${{ steps.extract.outputs.syft_version }}
  - golang-${{ steps.extract.outputs.golang_version }}-${{ steps.extract.outputs.debian_version}}
  - goreleaser-${{ steps.extract.outputs.goreleaser_version }}-${{ steps.extract.outputs.debian_version}}
  - cosign-${{ steps.extract.outputs.cosign_version }}-${{ steps.extract.outputs.debian_version}}
  - ko-${{ steps.extract.outputs.ko_version }}-${{ steps.extract.outputs.debian_version}}
  - trivy-${{ steps.extract.outputs.trivy_version }}-${{ steps.extract.outputs.debian_version}}
  - syft-${{ steps.extract.outputs.syft_version }}-${{ steps.extract.outputs.debian_version}}
```

With 13 tags like this, it is not convenient to maintain a space separated list.
If I take the same 13 tags above and convert this list into a single oneliner like below, this becomes unreadable and unmaintable.

```
golang-${{ steps.extract.outputs.golang_version }} goreleaser-${{ steps.extract.outputs.goreleaser_version }} cosign-${{ steps.extract.outputs.cosign_version }} ko-${{ steps.extract.outputs.ko_version }} trivy-${{ steps.extract.outputs.trivy_version }} syft-${{ steps.extract.outputs.syft_version }} golang-${{ steps.extract.outputs.golang_version }}-${{ steps.extract.outputs.debian_version}} goreleaser-${{ steps.extract.outputs.goreleaser_version }}-${{ steps.extract.outputs.debian_version}} cosign-${{ steps.extract.outputs.cosign_version }}-${{ steps.extract.outputs.debian_version}} ko-${{ steps.extract.outputs.ko_version }}-${{ steps.extract.outputs.debian_version}} trivy-${{ steps.extract.outputs.trivy_version }}-${{ steps.extract.outputs.debian_version}} syft-${{ steps.extract.outputs.syft_version }}-${{ steps.extract.outputs.debian_version}}
```

#### How does `docker` do for their own docker action?

Below is an example of how [docker/metadata-action](https://github.com/docker/metadata-action) handle the tags.
They do not rely on a YAML list. However, it is easier to write tags on multilines. Check the full example [here](https://github.com/ThalesGroup/goreleaser-glibc-image/blob/72e4b74e8cd29df3e30d5223a455eb076e679822/.github/workflows/base-container-build.yaml#L94).

This below is more readable than a single oneliner.

```yaml
      - name: Container metadata and tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          # image name may contain lowercase letters, digits and separators https://github.com/docker/metadata-action/tree/v5/?tab=readme-ov-file#image-name-and-tag-sanitization
          images: ${{ steps.set-oci-image-url.outputs.oci_image_url }}
          tags: |
            type=ref,event=branch
            # use tools version as tags
            type=raw,value=golang-${{ steps.extract.outputs.golang_version }}
            type=raw,value=goreleaser-${{ steps.extract.outputs.goreleaser_version }}
            type=raw,value=cosign-${{ steps.extract.outputs.cosign_version }}
            type=raw,value=ko-${{ steps.extract.outputs.ko_version }}
            type=raw,value=trivy-${{ steps.extract.outputs.trivy_version }}
            type=raw,value=syft-${{ steps.extract.outputs.syft_version }}

            type=raw,value=golang-${{ steps.extract.outputs.golang_version }}-${{ steps.extract.outputs.debian_version}}
            type=raw,value=goreleaser-${{ steps.extract.outputs.goreleaser_version }}-${{ steps.extract.outputs.debian_version}}
            type=raw,value=cosign-${{ steps.extract.outputs.cosign_version }}-${{ steps.extract.outputs.debian_version}}
            type=raw,value=ko-${{ steps.extract.outputs.ko_version }}-${{ steps.extract.outputs.debian_version}}
            type=raw,value=trivy-${{ steps.extract.outputs.trivy_version }}-${{ steps.extract.outputs.debian_version}}
            type=raw,value=syft-${{ steps.extract.outputs.syft_version }}-${{ steps.extract.outputs.debian_version}}

            # minimal (short sha)
            type=sha
            # full length sha
            type=sha,format=long
```

### Additional context

In [redhat-actions/buildah-build](https://github.com/redhat-actions/buildah-build), there is a `tags` field which is a space separated list. [Source](https://github.com/redhat-actions/push-to-registry/blob/5ed88d269cf581ea9ef6dd6806d01562096bee9c/README.md?plain=1#L29):

```yaml
tags: A space-separated list of the tags that were applied to the new image.
```

It is the same for [redhat-actions/push-to-registry](https://github.com/redhat-actions/push-to-registry#image-tag-inputs):

```
| tags | The tag or tags of the image or manifest to push. For multiple tags, separate by whitespace. Refer to [Image and Tag Inputs](https://github.com/redhat-actions/push-to-registry#image-tag-inputs). | `latest`
```

#### Kaniko deprecation

The deprecation of [`Kaniko`](https://github.com/GoogleContainerTools/kaniko/issues/3348) is a motivation to replace `Kaniko` with `podman` and `buildah`.

#### Use `podman` rather than `docker`

Why not use `docker` since it is available in [Ubuntu actions/runner-images](https://github.com/actions/runner-images/blob/6d67eed16270dd488fdc1d819f19246993d7e0dd/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L73-L77)?

Because my workflow is using `podman`.

And because [Podman](https://github.com/actions/runner-images/blob/6d67eed16270dd488fdc1d819f19246993d7e0dd/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L96), [skopeo](https://github.com/actions/runner-images/blob/6d67eed16270dd488fdc1d819f19246993d7e0dd/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L98C3-L98C9) and [Buildah](https://github.com/actions/runner-images/blob/6d67eed16270dd488fdc1d819f19246993d7e0dd/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L70) are all available in Github Actio Ubuntu 24.04 image.

Why not use docker github actions like [docker/metadata-action](https://github.com/docker/metadata-action)?

Because I do not want to mix Github Action that rely on the `docker` CLI client with Github Actions that rely on `podman` and `buildah`.

**Comment by snecklifter** [comment]
This already works. The `tags` input is parsed by splitting on whitespace (`tags.trim().split(/\s+/)`), which includes newlines. So you can use multi-line YAML strings:

```yaml
- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    tags: |
      latest
      v1.0.0
      v1
```

Note that GitHub Actions inputs are always strings, so true YAML list syntax (`- item`) is not supported by the Actions framework — but the multi-line string with `|` achieves the same result and is arguably cleaner than space-separated values.
