### ISSUE TITLE
Multi-arch support

### ISSUE THREAD

**Issue by lexfrei** [redhat-actions/buildah-build#24]
Looks like the buildah can build multi-arch images: https://github.com/containers/buildah/issues/1590
Can we use it in this action?

**Comment by Divyansh42** [comment]
@lexfrei 👋🏻
I think support to build mult-arch images will be a good addition.
We will update you once we start working on this feature :)

**Comment by tetchel** [comment]
is this just the `-arch` argument? 

this user also points out you need to have `qemu-user-static` installed
https://github.com/containers/buildah/issues/1590#issuecomment-771924743

**Comment by Divyansh42** [comment]
Hi @lexfrei this feature is now added in `v2` version of the action.

**Comment by anthr76** [comment]
Hi!

I'm trying to initiate a multi-arch build though it's failing.

My failed workflow can be found [here](https://github.com/anthr76/tooling/runs/2043473892?check_suite_focus=true)

I have set.

```
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.2.1
      with:
        image: tumbleweed-dnf-toolbox
        tags: ${{ env.SHORT_SHA }} ${{ env.SNAPSHOT }} latest
        archs: amd64,ARM64
        oci: true
        context: images/opensuse/tw/dnf
        dockerfiles:
          ./images/opensuse/tw/dnf/Dockerfile
 ```
 
 I can build just fine on the CLI like `buildah bud --arch amd64,ARM64 -t anthr76-devops-toolbox:20210305 .`
