### ISSUE TITLE
[BUG] `oci: true` still runs `buildah bud`

### ISSUE THREAD

**Issue by iapicca** [redhat-actions/buildah-build#79]
### Version

`redhat-actions/buildah-build@v2`

### Describe the bug

(I'm a noob and it's probably my fault)

setting `oci: true` in the workflow runs `buildah bud` and not `buildah build` anyway

### Steps to reproduce, workflow links, screenshots

<details>
<summary>workflow</summary>

```yaml
name: Test image

on:
 pull_request:

jobs:
  test_build:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: redhat-actions/buildah-build@v2
        with:
          image: test-image
          tags: v1 ${{ github.sha }}
          oci: true
          containerfiles: |
            ./build.sh
```

</details>
<details>
<summary>logs</summary>

```console
Run redhat-actions/buildah-build@v2
/usr/bin/buildah version
Overriding storage mount_program with "fuse-overlayfs" in environment
Performing build from Containerfile
/usr/bin/buildah bud -f /home/runner/work/flutter_development_container/flutter_development_container/build.sh --format oci -t test-image:v1 /home/runner/work/flutter_development_container/flutter_development_container
no FROM statement found
time="2021-10-11T19:14:36Z" level=error msg="exit status 125"
Error: Error: buildah exited with code 125
no FROM statement found
time="2021-10-11T19:14:36Z" level=error msg="exit status 125"
```

</details>

#

if you want to look at the repo here is the [link](https://github.com/iapicca/flutter_development_container/tree/test-workflow),
I'm really new to devops stuff so please understand
(also if you want to help me out I'd be very happy :) )
