### ISSUE TITLE
[QUESTION] Is it possible to use the `layers` to make this GHA reuse previously published image versions?

### ISSUE THREAD

**Issue by webknjaz** [redhat-actions/buildah-build#90]
### Question

Hi, I've seen an interesting trick at https://github.com/pyca/infra/blob/d52c449/.github/workflows/build-docker-images.yml#L58 where they use `docker build --cache-from=...` to have Docker reuse some of the layer cache from an earlier image version IIUC.

When I saw https://github.com/redhat-actions/buildah-build/pull/43 / https://github.com/redhat-actions/buildah-build/issues/42, I thought — would it be possible to do the same with podman/buildah? What would be required? Would `podman pull` coupled with `layers: true` be enough? Is there something I'm misunderstanding in how buildah works? (there probably is)

**Comment by webknjaz** [comment]
@divyansh42 @tetchel @lstocchi any comments?

**Comment by divyansh42** [comment]
Hey @webknjaz, apologies for the delayed response.
I've checked this, buildah doesn't support `--cache-from` yet. However, there is an open [issue](https://github.com/containers/buildah/issues/620) for that.

**Comment by webknjaz** [comment]
Yeah, I've seen some related issues but I still don't understand if that is something that direct invocations of `buildah` maybe support.

**Comment by webknjaz** [comment]
In particular, I was curious if that `layers` option does this.

**Comment by maokwen** [comment]
After [v1.27.0](https://github.com/containers/buildah/releases/tag/v1.27.0), buildah [support](containers/buildah#4118) `--cache-to` and `--cache-from`.

**Comment by np22-jpg** [comment]
> Can I use this GitHub Action and have a newer buildah version

GitHub Actions Images all use whatever is in the Ubuntu repos. When Lunar Lobster drops in a month, we'll get a newer version of buildah/podman/etc. If you'd like, you can use `quay.io/buildah/stable:latest`. I use something like this:
```
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable:latest
      options: --privileged
```
Although it's finicky, it gives you the latest version of buildah and dnf (but not podman?).

**Comment by lectrician1** [comment]
hhh well you can specify cache-to and cache-from now, but you need a system to make the right calls to the GitHub cache API (which i was trying to do) https://github.com/tonistiigi/go-actions-cache/blob/master/api.md and that system does not exist in buildah-build like it does in Docker's https://docs.docker.com/build/ci/github-actions/cache/#github-cache , so you might as well just use Docker's if you want caching

A near attempt:
```
name: 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Buildah Build
            uses: redhat-actions/buildah-build@v2
            with:
              containerfiles: |
                ./Containerfile
              image: yay
              layers: true
              build-args: |
                cache-to=NEED SPECIFIC CACHE URL WITH KEY
                cache-from=NEED SPECIFIC CACHE URL WITH KEY
              
          - name: Push To ghcr
            uses: redhat-actions/push-to-registry@v2
            with:
              image: ${{ steps.build-image.outputs.image }}
              tags: ${{ steps.build-image.outputs.tags }}
              registry: ghcr.io/${{ github.repository_owner }}
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              extra-args: |
                --disable-content-trust
 ```

**Comment by jan-matejka** [comment]
This seems to be fixed now

**Comment by snecklifter** [comment]
The `layers: true` input enables **local** layer caching — buildah will reuse layers from previous builds on the same runner if the build context and instructions haven't changed. This is useful for sequential builds within the same workflow or on persistent self-hosted runners.

However, it does **not** pull layers from a remote registry for cache reuse across different runners or workflow runs. GitHub-hosted runners are ephemeral, so local layer cache is lost after each job.

### For cross-run caching on GitHub-hosted runners

Buildah supports `--cache-from` and `--cache-to` (in newer versions) for remote cache backends. You can use these via `extra-args`:

```yaml
- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    containerfiles: ./Containerfile
    layers: true
    extra-args: |
      --cache-from=registry.example.com/my-image:cache
      --cache-to=registry.example.com/my-image:cache
```

**Note:** `--cache-from`/`--cache-to` require buildah 1.28+ and may need the image to be built with `--layers` enabled. The ubuntu-24.04 runner ships buildah 1.33.7 which supports this.

### Alternative: GitHub Actions cache

You can also cache buildah's local storage between workflow runs using `actions/cache`:

```yaml
- uses: actions/cache@v4
  with:
    path: |
      /var/lib/containers
    key: buildah-${{ runner.os }}-${{ hashFiles('**/Containerfile') }}
    restore-keys: |
      buildah-${{ runner.os }}-

- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    containerfiles: ./Containerfile
    layers: true
```

This preserves the local layer cache across runs, giving you the reuse you are looking for.
