### ISSUE TITLE
[FEATURE] automatic checkout

### ISSUE THREAD

**Issue by akostadinov** [redhat-actions/buildah-build#97]
### Is your feature request related to a problem? Please describe.

I want to have a shorter workflow file and skip `checkout` step when all needed is to just checkout source from current event.

For example with buildx I can have:
```yaml
...
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ inputs.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          file: openshift/system/Dockerfile
```

With buildah I need to do:
```yaml
- uses: actions/checkout@v3

- name: Build image
    id: build-image
    uses: redhat-actions/buildah-build@v2
    ...
```

### Describe the solution you'd like

Checkout to happen automatically.

**Comment by snecklifter** [comment]
Thank you for the suggestion. The established convention in GitHub Actions is for each action to have a single responsibility, and repository checkout is handled by `actions/checkout`. This separation is important because:

1. **Flexibility** — Users may need to check out a specific ref, submodules, fetch-depth, or multiple repositories. Embedding checkout logic would either limit these options or duplicate the complexity already handled by `actions/checkout`.
2. **Transparency** — Explicit steps make workflows easier to read and debug. A hidden checkout step could cause confusion when users need to understand what code is being built.
3. **Composability** — Some workflows don't need checkout at all (e.g., building from a Containerfile in a different repo, or using a pre-populated workspace from a previous job).

The recommended pattern is straightforward:

```yaml
- uses: actions/checkout@v7
- uses: redhat-actions/buildah-build@v2
  with:
    image: my-image
    containerfiles: ./Containerfile
```

This is consistent with how other build actions work (docker/build-push-action, etc.).
